SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE TABLE `ruststats` (
  `id` int(10) UNSIGNED NOT NULL,
  `server_id` smallint(6) NOT NULL,
  `steamid` varchar(20) NOT NULL,
  `name` varchar(50) NOT NULL,
  `playtime` int(11) NOT NULL COMMENT 'Playtime in seconds',
  `kills` mediumint(9) NOT NULL,
  `deaths` mediumint(9) NOT NULL,
  `kdr` float NOT NULL,
  `avatar` varchar(120) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `ruststats`
  ADD PRIMARY KEY (`id`),
  ADD KEY `steamid_index` (`steamid`);

ALTER TABLE `ruststats`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
